// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackForUBB.Repository.Context;

#nullable disable

namespace TrackForUBB.Repository.Migrations
{
    [DbContext(typeof(AcademicAppContext))]
    [Migration("20251125175654_RefactoredDomain")]
    partial class RefactoredDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PromotionSemesterId")
                        .HasColumnType("integer");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromotionSemesterId");

                    b.HasIndex("SubGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("integer");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Hour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("HourInterval")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("integer");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentSubGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentGroupId");

                    b.HasIndex("StudentSubGroupId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Hours");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EndYear")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialisationId")
                        .HasColumnType("integer");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecialisationId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.PromotionSemester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PromotionYearId")
                        .HasColumnType("integer");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromotionYearId");

                    b.ToTable("PromotionSemesters");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.PromotionYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PromotionId")
                        .HasColumnType("integer");

                    b.Property<int>("YearNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionYears");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Specialisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Specialisations");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.StudentSubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StudentGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("SubGroups");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumberOfCredits")
                        .HasColumnType("integer");

                    b.Property<int>("PromotionSemesterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromotionSemesterId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Classroom", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.Location", "Location")
                        .WithMany("Classrooms")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Enrollment", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.PromotionSemester", "PromotionSemester")
                        .WithMany("Enrollments")
                        .HasForeignKey("PromotionSemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackForUBB.Repository.EFEntities.StudentSubGroup", "SubGroup")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackForUBB.Repository.EFEntities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotionSemester");

                    b.Navigation("SubGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Grade", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.Enrollment", "Enrollment")
                        .WithMany("Grades")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackForUBB.Repository.EFEntities.PromotionSemester", "Semester")
                        .WithMany("Grades")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackForUBB.Repository.EFEntities.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Hour", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.Classroom", "Classroom")
                        .WithMany("Hours")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackForUBB.Repository.EFEntities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId");

                    b.HasOne("TrackForUBB.Repository.EFEntities.PromotionSemester", "Semester")
                        .WithMany("Hours")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackForUBB.Repository.EFEntities.StudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId");

                    b.HasOne("TrackForUBB.Repository.EFEntities.StudentSubGroup", "StudentSubGroup")
                        .WithMany()
                        .HasForeignKey("StudentSubGroupId");

                    b.HasOne("TrackForUBB.Repository.EFEntities.Subject", "Subject")
                        .WithMany("Hours")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackForUBB.Repository.EFEntities.Teacher", "Teacher")
                        .WithMany("Hours")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Promotion");

                    b.Navigation("Semester");

                    b.Navigation("StudentGroup");

                    b.Navigation("StudentSubGroup");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Location", b =>
                {
                    b.OwnsOne("TrackForUBB.Repository.EFEntities.GoogleMapsData", "GoogleMapsData", b1 =>
                        {
                            b1.Property<int>("LocationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Id")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("GoogleMapsData_Id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("GoogleMapsData_Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("GoogleMapsData_Longitude");

                            b1.HasKey("LocationId");

                            b1.ToTable("Locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.Navigation("GoogleMapsData");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Promotion", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.Specialisation", "Specialisation")
                        .WithMany("Promotions")
                        .HasForeignKey("SpecialisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialisation");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.PromotionSemester", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.PromotionYear", "PromotionYear")
                        .WithMany("PromotionSemesters")
                        .HasForeignKey("PromotionYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotionYear");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.PromotionYear", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.Promotion", "Promotion")
                        .WithMany("Years")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Specialisation", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.Faculty", "Faculty")
                        .WithMany("Specialisations")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.StudentGroup", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.Promotion", "Promotion")
                        .WithMany("StudentGroups")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.StudentSubGroup", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.StudentGroup", "StudentGroup")
                        .WithMany("StudentSubGroups")
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Subject", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.PromotionSemester", "PromotionSemester")
                        .WithMany("Subjects")
                        .HasForeignKey("PromotionSemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotionSemester");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Teacher", b =>
                {
                    b.HasOne("TrackForUBB.Repository.EFEntities.Faculty", "Faculty")
                        .WithMany("Teachers")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackForUBB.Repository.EFEntities.User", "User")
                        .WithOne()
                        .HasForeignKey("TrackForUBB.Repository.EFEntities.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Classroom", b =>
                {
                    b.Navigation("Hours");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Enrollment", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Faculty", b =>
                {
                    b.Navigation("Specialisations");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Location", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Promotion", b =>
                {
                    b.Navigation("StudentGroups");

                    b.Navigation("Years");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.PromotionSemester", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Grades");

                    b.Navigation("Hours");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.PromotionYear", b =>
                {
                    b.Navigation("PromotionSemesters");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Specialisation", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.StudentGroup", b =>
                {
                    b.Navigation("StudentSubGroups");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.StudentSubGroup", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Subject", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Hours");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.Teacher", b =>
                {
                    b.Navigation("Hours");
                });

            modelBuilder.Entity("TrackForUBB.Repository.EFEntities.User", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
